import type { Metadata } from 'next'
import { Figtree } from 'next/font/google'

import '@/app/globals.css'
import { Player } from '@/components/player'
import { Sidebar } from '@/components/sidebar'
import { Providers } from '@/components/providers'
import { AuthDialog } from '@/components/auth-dialog'
import { UploadDialog } from '@/components/upload-dialog'
import { SubscribeDialog } from '@/components/subscribe-dialog'
import { getSongsByUserId } from '@/actions/get-songs-by-user-id'
import { getActiveProductsWithPrices } from '@/actions/get-active-products-with-prices'

const font = Figtree({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Spotify Clone',
  description: 'Generated by create next app',
}

export const revalidate = 0

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const userSongs = await getSongsByUserId()
  const products = await getActiveProductsWithPrices()

  return (
    <html lang='en'>
      <body className={font.className}>
        <Providers>
          <Sidebar songs={userSongs}>
            <Player />
            <AuthDialog />
            <UploadDialog />
            <SubscribeDialog products={products} />
            {children}
          </Sidebar>
        </Providers>
      </body>
    </html>
  )
}
